### ISSUE TITLE
site:[Kruszonka] ANIMAL ROLES

### ISSUE THREAD

**Issue by pikulet** [BeyonderMafia/Ultimafia#389]
FOR THE LOVE OF LUCID STOP CREATING ANIMAL ROLES, THIS IS A MAFIA GAME IT'S FOR HUMANS NOT GODDAMN FURRY ANIMALS HOW THE HELL IS A POLAR BEAR MAFIA IT'S A BEAR WHO IS RESPONSIBLE FOR THIS

**Comment by DrSharky** [comment]
Ok
